#
# Effort
#
- name: "effort: epic"
  color: "2b3d19"
  description: "Multi-stage task that may require multiple PRs."
- name: "effort: high"
  color: "668d3b"
  description: "Large or difficult task."
- name: "effort: medium"
  color: "91ca55"
  description: "Default level of effort."
- name: "effort: low"
  color: "c8e5aa"
  description: "Easy or tiny task that takes less than a day."
#
# Priority
#
- name: "priority: 0"
  color: "ac2e3b"
  description: "Do this first before everything else. This is critical and nothing works without this."
- name: "priority: 1"
  color: "d73a4a"
  description: "This is important. It should be dealt with shortly."
- name: "priority: 2"
  color: "e37580"
  description: "We will do our best to deal with this."
- name: "priority: 3"
  color: "efb0b7"
  description: "Nice-to-have. Willing to ship without this."
#
# Type
#
- name: "type: ai"
  color: "ff1493"
  description: "AI-related features or changes."
- name: "type: bug"
  color: "d73a4a"
  description: "Something isn't working."
- name: "type: build"
  color: "fef2c0"
  description: "Changes that affect the build system or external dependencies."
- name: "type: chore"
  color: "7c7f81"
  description: "Maintenance work."
- name: "type: ci"
  color: "a2765d"
  description: "Changes to our CI configuration files and scripts."
- name: "type: docs"
  color: "0075ca"
  description: "Changes to documentation."
- name: "type: feature"
  color: "7fdbe0"
  description: "New feature or request."
- name: "type: perf"
  color: "f9904f"
  description: "Change that improves performance or user experience."
- name: "type: refactor"
  color: "c5def5"
  description: "Change that neither fixes a bug nor adds a feature."
- name: "type: style"
  color: "d876e3"
  description: "Changes that do not affect the meaning of the code."
- name: "type: test"
  color: "e0a381"
  description: "Adding, updating, or removing tests."
#
# Work
#
- name: "work: chaotic"
  color: "81232c"
  description: "Act-sense-respond. No clear relationship between cause and effect."
- name: "work: complex"
  color: "d4c5f9"
  description: "Probe-sense-respond. The relationship between cause and effect can only be perceived in retrospect."
- name: "work: complicated"
  color: "fbca04"
  description: "Sense-analyze-respond. The relationship between cause and effect requires analysis or expertise."
- name: "work: clear"
  color: "91ca55"
  description: "Sense-categorize-respond. The relationship between cause and effect is clear."
#
# Miscellaneous
#
- name: "duplicate"
  color: "a6a9ac"
  description: "This issue or pull request already exists."
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers."
- name: "help"
  color: "008672"
  description: "Extra information is needed."
- name: "stale"
  color: "cfd3d7"
  description: "Inactive for a long time."
